### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by CVDOU** [sooyekim/Deep-SR-ITM#15]
As mentioned in your paper, you totally have 44k frames for training. During training, 20-40 patches are  randomly cropped from each image. So it should have more than than 880K patches. But your uploaded training dataset only contains 39840 patches. 

Could you share the detail to generate the 39840 patches? How to sample the images/patches?

**Comment by sooyekim** [comment]
Hi @CVDOU ,

Thanks for the interest in our work!

As you mentioned,  20-40 patches were randomly cropped from each image.
Also as mentioned in the paper, patches were extracted with a frame stride ranging from 10 to 80 to avoid high coherence among the frames.

I tried to extract more patches/frame if the video was spatially complex, and increased the frame stride if the video had long scenes (which are likely to contain similar content within the scenes) or if there weren't a lot of variation in the scenes.

Specifically among the training videos that I used (see [this comment](https://github.com/sooyekim/Deep-SR-ITM/issues/8#issuecomment-564816839)):
    **LG Colors of Journey HDR UHD 4K Demo** (6,899 frames)
        - patches/frame: 30, frame stride: 20, until 6,260-th frame
    **LG New York HDR UHD 4K Demo** (1,806 frames)
        - patches/frame: 40, frame stride: 10, until 1,700-th frame
    **Samsung & RedBull See the Unexpected HDR UHD 4K Demo** (11,849 frames)
        - patches/frame: 20, frame stride: 80, until 11,772-th frame
    **Samsung Chasing The Light HDR UHD 4K Demo** (5,672 frames)
        - patches/frame: 30, frame stride: 20, until last (5,672-th) frame
    **Samsung Travel With My Pet HDR UHD 4K Demo** (60 FPS) (9,274 frames)
        - patches/frame: 20, frame stride: 40, until last (9,274-th) frame
    **Samsung Wonderland HDR UHD 4K Demo** (3,864 frames)
        - patches/frame: 30, frame stride: 30, until last (3,864-th) frame
    **Sony Bravia OLED HDR UHD 4K Demo** (4,980 frames)
        - patches/frame: 30, frame stride: 40, until 4,850-th frame

For some videos, I didn't collect the data until the last frame since they contained fade-outs with mostly black frames that seemed not very helpful for training (eg. black background with company logos).

Hope this helps & please LMK if you have any other questions!

Thanks,
Soo Ye

**Comment by CVDOU** [comment]
Thanks a lot.
