### ISSUE TITLE
Wanting original image 

### ISSUE THREAD

**Issue by Beta233** [sooyekim/Deep-SR-ITM#8]
Hi,there, could please share the original training image? So that I can process the image randomly to avoid overfiting problem.

**Comment by sooyekim** [comment]
Hi @Beta233 ,

Thanks for the interest in our work.

The original videos are too large to upload since they are ~60K frames of 4K resolution.

But I can tell you the list of videos I used:
&nbsp; &nbsp; LG Colors of Journey HDR UHD 4K Demo (6,899 frames)
&nbsp; &nbsp; LG Cymatic Jazz HDR HLG UHD 4K Demo (9,504 frames) - **TEST**
&nbsp; &nbsp; LG Daylight HDR UHD 4K Demo (2,860 frames) - **TEST**
&nbsp; &nbsp; LG New York HDR UHD 4K Demo (1,806 frames)
&nbsp; &nbsp; Samsung & RedBull See the Unexpected HDR UHD 4K Demo (11,849 frames)
&nbsp; &nbsp; Samsung Chasing The Light HDR UHD 4K Demo (5,672 frames)
&nbsp; &nbsp; Samsung Travel With My Pet HDR UHD 4K Demo (60 FPS) (9,274 frames)
&nbsp; &nbsp; Samsung Wonderland HDR UHD 4K Demo (3,864 frames)
&nbsp; &nbsp; Samsung Wonderland Two HDR UHD 4K Demo (3,110 frames) - **TEST**
&nbsp; &nbsp; Sony Bravia OLED HDR UHD 4K Demo (4,980 frames)

&nbsp; &nbsp; Total 59,818 frames

The videos marked as **TEST** were left for testing, and the rest of the videos were used for training.

They can be found on Youtube, but for higher quality I downloaded the HDR videos on 4kmedia.org website, and downloaded their Youtube-tone-mapped SDR version on Youtube.

Thanks,
Soo Ye

**Comment by chxy95** [comment]
> Hi @Beta233 ,
> 
> Thanks for the interest in our work.
> 
> The original videos are too large to upload since they are ~60K frames of 4K resolution.
> 
> But I can tell you the list of videos I used:
>     LG Colors of Journey HDR UHD 4K Demo (6,899 frames)
>     LG Cymatic Jazz HDR HLG UHD 4K Demo (9,504 frames) - **TEST**
>     LG Daylight HDR UHD 4K Demo (2,860 frames) - **TEST**
>     LG New York HDR UHD 4K Demo (1,806 frames)
>     Samsung & RedBull See the Unexpected HDR UHD 4K Demo (11,849 frames)
>     Samsung Chasing The Light HDR UHD 4K Demo (5,672 frames)
>     Samsung Travel With My Pet HDR UHD 4K Demo (60 FPS) (9,274 frames)
>     Samsung Wonderland HDR UHD 4K Demo (3,864 frames)
>     Samsung Wonderland Two HDR UHD 4K Demo (3,110 frames) - **TEST**
>     Sony Bravia OLED HDR UHD 4K Demo (4,980 frames)
> 
>     Total 59,818 frames
> 
> The videos marked as **TEST** were left for testing, and the rest of the videos were used for training.
> 
> They can be found on Youtube, but for higher quality I downloaded the HDR videos on 4kmedia.org website, and downloaded their Youtube-tone-mapped SDR version on Youtube.
> 
> Thanks,
> Soo Ye

So the pairs is made up of Youtube SDR videos and 4kmedia.org HDR videos? Is it right?

**Comment by chxy95** [comment]
> Hi @Beta233 ,
> 
> Thanks for the interest in our work.
> 
> The original videos are too large to upload since they are ~60K frames of 4K resolution.
> 
> But I can tell you the list of videos I used:
>     LG Colors of Journey HDR UHD 4K Demo (6,899 frames)
>     LG Cymatic Jazz HDR HLG UHD 4K Demo (9,504 frames) - **TEST**
>     LG Daylight HDR UHD 4K Demo (2,860 frames) - **TEST**
>     LG New York HDR UHD 4K Demo (1,806 frames)
>     Samsung & RedBull See the Unexpected HDR UHD 4K Demo (11,849 frames)
>     Samsung Chasing The Light HDR UHD 4K Demo (5,672 frames)
>     Samsung Travel With My Pet HDR UHD 4K Demo (60 FPS) (9,274 frames)
>     Samsung Wonderland HDR UHD 4K Demo (3,864 frames)
>     Samsung Wonderland Two HDR UHD 4K Demo (3,110 frames) - **TEST**
>     Sony Bravia OLED HDR UHD 4K Demo (4,980 frames)
> 
>     Total 59,818 frames
> 
> The videos marked as **TEST** were left for testing, and the rest of the videos were used for training.
> 
> They can be found on Youtube, but for higher quality I downloaded the HDR videos on 4kmedia.org website, and downloaded their Youtube-tone-mapped SDR version on Youtube.
> 
> Thanks,
> Soo Ye

So the pairs are made up of Youtube SDR videos and 4kmedia.org HDR videos? Is it right?
It seems like there are only tone-mapped SDR videos on Youtube.

**Comment by sooyekim** [comment]
Hi @chxy95 ,

If you're using a YouTube downloading software, usually there are multiple quality options where some are SDR and some are HDR. It's not tagged on the option but you can check the file after the download. 

However, since 4kmedia.org has higher quality HDR videos, it's better to use the HDR videos from 4kmedia.org (and SDR videos from Youtube).

Thanks,
Soo Ye

**Comment by ZaixiS** [comment]
Hi @sooyekim,

Your work is great! And thank you so much for so many details!
I wonder if you have checked the license for those videos from 4kmedia.org. Since I am trying to build some HDR video databases but I can't find any relevant information on the website. I can't find any contact information either. I wonder if you had the same concern before and if you have addressed them?
Thanks!
Zaixi

**Comment by sooyekim** [comment]
Hi @ZaixiS , 
I'm not really sure about the licensing information. I also couldn't find any info on the website..
Sorry that I couldn't be of much help!

**Comment by ZaixiS** [comment]
Hi @sooyekim ,

Thanks for your reply! I guess it's fine then! I wish to use these resources too!

**Comment by haifangqin** [comment]
hi, Could you provide the corresponding SDR video download link ?  Is it mean the 720P on youtube?

**Comment by sooyekim** [comment]
@haifangqin We downloaded their 4K SDR versions and downsampled them by 2 and 4 using bicubic downsampling, resulting in 1920x1080 and 960x540 resolutions. For better quality videos, you could try searching them on 4kmedia.org. Note that we cannot provide the download links as they are not ours to distribute.
