### ISSUE TITLE
How to reproduce the horizontal and vertical 1D filter?

### ISSUE THREAD

**Issue by liulizhou** [sooyekim/Deep-SR-ITM#9]
Hi, @sooyekim 
I'm reading your paper 'JSI-GAN'. I have a question.
horizontal and vertical 1D filter produce like this:
```
horizontal 1D=(Conv◦RL◦RB^4◦Conv)(Xd)
```
I don't understand how to produce the horizontal and vertical 1D filter by two kinds of `conv layer` ? Can you explain that ?

Thanks!
Liu Lizhou

**Comment by sooyekim** [comment]
Hi @liulizhou ,

Thanks for the interest in our recent paper!

We regard the produced HxWx(41xscalexscale)-sized 3D tensor as 1D filters of size 41xscalexscale at each pixel grid location in HxW. Since these 1D filters are applied as inner products at each location, the network is trained to produce appropriate filter values for the 3D tensor that minimizes the final loss.

Please note that we plan on releasing the code by early February, before the AAAI conference starts :)

Best,
Soo Ye
